In [139]:
import numpy as np
import pandas as pd

In [140]:
games.head(10)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
1,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
2,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
3,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
4,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
5,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
6,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
7,Call of Duty: Black Ops II,X360,2012.0,Shooter,Activision,8.25,4.30,0.07,1.12,13.73
8,Call of Duty: Modern Warfare 2,X360,2009.0,Shooter,Activision,8.52,3.63,0.08,1.29,13.51
9,Call of Duty: Modern Warfare 3,PS3,2011.0,Shooter,Activision,5.54,5.82,0.49,1.62,13.46

In [141]:
studios = games.loc[:,['Genre','Publisher','Global_Sales']]

In [142]:
studios

             Genre               Publisher  Global_Sales
0             Misc  Microsoft Game Studios         21.82
1           Action    Take-Two Interactive         21.40
2           Action    Take-Two Interactive         16.38
3          Shooter              Activision         14.76
4          Shooter              Activision         14.64
...            ...                     ...           ...
3138  Role-Playing                     NaN          0.01
3139      Platform             Deep Silver          0.01
3140       Shooter                  Capcom          0.01
3141    Simulation       UIG Entertainment          0.01
3142        Sports    Alternative Software          0.01

[3143 rows x 3 columns]

In [143]:
studios.groupby('Publisher').sum().sort_values('Global_Sales', ascending = True)

                        Global_Sales
Publisher
UIG Entertainment               0.01
Nitroplus                       0.01
Stainless Games                 0.01
Epic Games                      0.01
ChunSoft                        0.01
...                              ...
Microsoft Game Studios        190.56
Ubisoft                       201.98
Take-Two Interactive          218.08
Activision                    349.22
Electronic Arts               434.41

[155 rows x 1 columns]

In [144]:
# which are the top publishers within each genre by global sales

In [148]:
studios.groupby(['Genre','Publisher']).sum().sort_values(by = 'Global_Sales',ascending = False)

                                         Global_Sales
Genre        Publisher
Shooter      Activision                        245.46
Sports       Electronic Arts                   203.50
Action       Take-Two Interactive              106.04
             Ubisoft                            96.44
Shooter      Electronic Arts                    92.58
...                                               ...
Adventure    Cave                                0.01
Role-Playing TopWare Interactive                 0.01
Sports       Interworks Unlimited, Inc.          0.01
Strategy     Ackkstudios                         0.01
Adventure    Views                               0.01

[422 rows x 1 columns]